// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI2ReNA1sZbHWZFJJT0FJwL72SbaXRb5o',
    appId: '1:128239747293:web:74502f508cb805395b5b34',
    messagingSenderId: '128239747293',
    projectId: 'game-project-416',
    authDomain: 'game-project-416.firebaseapp.com',
    storageBucket: 'game-project-416.firebasestorage.app',
    measurementId: 'G-ZYY6J7YQHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApA-JhhQouq7SYyz3xMo5-EbqDzC0FqU4',
    appId: '1:128239747293:android:484260e83f5ac0025b5b34',
    messagingSenderId: '128239747293',
    projectId: 'game-project-416',
    storageBucket: 'game-project-416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcH56sJOCfJrumNkon5dAvxQv9Ub4NZos',
    appId: '1:128239747293:ios:eef05b42199cb5a25b5b34',
    messagingSenderId: '128239747293',
    projectId: 'game-project-416',
    storageBucket: 'game-project-416.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcH56sJOCfJrumNkon5dAvxQv9Ub4NZos',
    appId: '1:128239747293:ios:eef05b42199cb5a25b5b34',
    messagingSenderId: '128239747293',
    projectId: 'game-project-416',
    storageBucket: 'game-project-416.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI2ReNA1sZbHWZFJJT0FJwL72SbaXRb5o',
    appId: '1:128239747293:web:b28e231fe4f9fce15b5b34',
    messagingSenderId: '128239747293',
    projectId: 'game-project-416',
    authDomain: 'game-project-416.firebaseapp.com',
    storageBucket: 'game-project-416.firebasestorage.app',
    measurementId: 'G-G3ECENLE2K',
  );
}
